/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

/**
 *
 * @author Haris Khan
 */
public class dashBoard extends javax.swing.JFrame {

    /**
     * Creates new form dashBoard
     */
    public dashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addStudent = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        addTeacher = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        addResult = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addReport = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        viewStudents = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        viewTeachers = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ViewResult = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        viewReport = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 182, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/icons8-school-96.png"))); // NOI18N

        jLabel2.setText("School Name");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        jLabel3.setText("School Mangement System");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("______________________________________________________________________________________________________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 190));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 174, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1540, -1));

        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/add students.png"))); // NOI18N
        addStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentMouseClicked(evt);
            }
        });
        jPanel2.add(addStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 101, 105));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Add Student");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 129, 33));

        addTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/add teacher.png"))); // NOI18N
        addTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTeacherMouseClicked(evt);
            }
        });
        jPanel2.add(addTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 210, 90));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Add Teacher");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 129, 33));

        addResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/add result.png"))); // NOI18N
        addResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addResultMouseClicked(evt);
            }
        });
        jPanel2.add(addResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 160, 90));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Add Result");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 129, 33));

        addReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/add report.png"))); // NOI18N
        addReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportMouseClicked(evt);
            }
        });
        jPanel2.add(addReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 70, 120, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/attendence.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 80, 110, 90));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Mark Attendence");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 180, 190, 33));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Add Fee Report");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 190, 33));

        viewStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/view students.png"))); // NOI18N
        viewStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewStudentsMouseClicked(evt);
            }
        });
        jPanel2.add(viewStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 150, 102));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("View Student");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 129, 33));

        viewTeachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/view teacher.png"))); // NOI18N
        viewTeachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTeachersMouseClicked(evt);
            }
        });
        jPanel2.add(viewTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 200, 90));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("View Teacher");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 129, 33));

        ViewResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/view result.png"))); // NOI18N
        ViewResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewResultMouseClicked(evt);
            }
        });
        jPanel2.add(ViewResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 140, 210));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("View Result");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 129, 33));

        viewReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/view report.png"))); // NOI18N
        viewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewReportMouseClicked(evt);
            }
        });
        jPanel2.add(viewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 140, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Logout");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 490, 190, 33));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/icons8-shutdown-100.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 380, 110, 100));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("View Fee Report");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 190, 33));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1540, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void addStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentMouseClicked
        // TODO add your handling code here:
        addStudent as = new addStudent();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_addStudentMouseClicked

    private void addTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherMouseClicked
        // TODO add your handling code here:
        addTeacher at = new addTeacher();
        at.setVisible(true);
        dispose();
    }//GEN-LAST:event_addTeacherMouseClicked

    private void addResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addResultMouseClicked
        // TODO add your handling code here:
        addResult ar = new addResult();
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_addResultMouseClicked

    private void addReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportMouseClicked
        // TODO add your handling code here:
        addReport ar = new addReport();
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_addReportMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        attendence a = new attendence();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void viewStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStudentsMouseClicked
        // TODO add your handling code here:
        viewStudent vs = new viewStudent();
        vs.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewStudentsMouseClicked

    private void viewTeachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTeachersMouseClicked
        // TODO add your handling code here:
        viewTeacher vt = new viewTeacher();
        vt.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewTeachersMouseClicked

    private void ViewResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewResultMouseClicked
        // TODO add your handling code here:
        viewResult vr = new viewResult();
        vr.setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewResultMouseClicked

    private void viewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReportMouseClicked
        // TODO add your handling code here:
        viewReport vr = new viewReport();
        vr.setVisible(true);
        dispose();

    }//GEN-LAST:event_viewReportMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        schoolLogin sl = new schoolLogin();
        sl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewResult;
    private javax.swing.JLabel addReport;
    private javax.swing.JLabel addResult;
    private javax.swing.JLabel addStudent;
    private javax.swing.JLabel addTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel viewReport;
    private javax.swing.JLabel viewStudents;
    private javax.swing.JLabel viewTeachers;
    // End of variables declaration//GEN-END:variables
}
